"""Added Profile Img Upload Field

Revision ID: 143352721b47
Revises: a890f101f32f
Create Date: 2024-08-21 17:32:52.793923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143352721b47'
down_revision = 'a890f101f32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_img', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_img')

    # ### end Alembic commands ###
