"""empty message

Revision ID: 299a0bd9f973
Revises: 5d1d1d3c3a25
Create Date: 2025-03-22 18:25:14.310154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299a0bd9f973'
down_revision = '5d1d1d3c3a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('content')
        batch_op.drop_column('modified_last')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_last', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    op.drop_table('todo')
    # ### end Alembic commands ###
