"""empty message

Revision ID: 8b1a1c06152d
Revises: e14b094530a7
Create Date: 2025-03-28 21:39:14.832877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1a1c06152d'
down_revision = 'e14b094530a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('zip',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('zip',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###
