"""Add cover_image to Project model

Revision ID: 9c014182b3cb
Revises: f64fe0a4b119
Create Date: 2025-04-12 13:38:20.392807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c014182b3cb'
down_revision = 'f64fe0a4b119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
