"""empty message

Revision ID: d20e71e6a8e7
Revises: 3b1331cd52c0
Create Date: 2025-03-24 22:33:48.014790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd20e71e6a8e7'
down_revision = '3b1331cd52c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('date_made', sa.Date(), nullable=True),
    sa.Column('progress', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_progress')
    # ### end Alembic commands ###
