"""empty message

Revision ID: f64fe0a4b119
Revises: 021bbdc39fbe
Create Date: 2025-04-07 21:40:08.966119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f64fe0a4b119'
down_revision = '021bbdc39fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_discussion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ProjectMembership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=30), nullable=True))
        batch_op.drop_column('date_joined')
        batch_op.drop_column('roles')

    with op.batch_alter_table('Upvotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvoted_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_upvoted')

    with op.batch_alter_table('task_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_assigned')

    with op.batch_alter_table('task_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('made_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_made')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_joined')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_joined', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('joined_at')

    with op.batch_alter_table('task_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_made', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('made_at')

    with op.batch_alter_table('task_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_assigned', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('assigned_at')

    with op.batch_alter_table('Upvotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_upvoted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('upvoted_at')

    with op.batch_alter_table('ProjectMembership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', postgresql.ARRAY(sa.VARCHAR(length=30)), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_joined', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('role')
        batch_op.drop_column('joined_at')

    op.drop_table('project_discussion')
    # ### end Alembic commands ###
